config/routes.rb
ApolloApp::Application.routes.draw do

  root 'users#index'
  get 'auth_user' => 'users#auth'
  post 'create_user' => 'users#create'
  get 'login_user' => 'sessions#create'
  resources :users
  get 'destroy_session' => 'sessions#destroy', as: :destory_session
  post 'create_playlist' => 'playlists#create'
  get 'single_playlist_fetch' => 'playlists#single_fetch'
  post 'add_song' => 'songs#create'
  post 'remove_song' => 'songs#remove'
  post 'favorite_song' => 'songs#favorite'
  post 'unfavorite_song' => 'songs#unfavorite'
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :playlist_permissions
  has_many :playlists, through: :playlist_permissions
  has_many :playlist_orders
  has_many :songs, through: :playlist_orders

  validates :name, presence: true

end

app/models/playlist_order.rb
class PlaylistOrder < ActiveRecord::Base
  belongs_to :playlist
  belongs_to :song
end

app/models/playlist_permission.rb
class PlaylistPermission < ActiveRecord::Base
  belongs_to :playlist
  belongs_to :user

end

app/models/song.rb
class Song < ActiveRecord::Base
  has_many :playlist_orders
  has_many :playlists, through: :playlist_orders
  belongs_to :user
  
  validates :url, presence: true

  before_update :capitalize

  def favorites
    song_id = self.id
    return Favorite.where(song_id: song_id)
  end

  def capitalize
    self.title = self.title.split(' ').map {|w| w.capitalize }.join(' ')
    self.artist = self.artist.split(' ').map {|w| w.capitalize }.join(' ')
  end
  
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
	before_save :encrypt_password
	before_create { generate_token(:auth_token) }
	include BCrypt
	attr_accessor :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  has_many :playlist_permissions
  has_many :playlists, through: :playlist_permissions
  has_many :songs
	after_create :first_playlists


	def generate_token(column)
		begin 
			token = SecureRandom.urlsafe_base64
			self[column] = token
		end while User.exists?(column => self[column])
	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_digest = BCrypt::Engine.hash_secret(password, self.password_salt)
		else
			nil
		end
	end	

	def self.authenticate(email, password)
		user = self.find_by_email(email)
		if user && user.password_digest == ::BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end

  def favorites
    user_id = self.id
    return Favorite.where(user_id: user_id)
  end

	private 
	
  def first_playlists
    self.playlists << Playlist.create(name: "All")
    self.playlists << Playlist.create(name: "Favorites")
    self.playlists << Playlist.create(name: "Shared")
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
  	if cookies[:auth_token]
  		@current_user = @current_user || User.find_by_auth_token(cookies[:auth_token]) if cookies[:auth_token]
  	else
  		nil
  	end
  end


end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def create
    if current_user
      @playlist = current_user.playlists.create(name: params["name"])
    end
    respond_to do |format|
        format.js
    end
  end

  def single_fetch
    @playlist = Playlist.find(params["playlist_id"])
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      cookies.permanent[:auth_token] = user.auth_token
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      redirect_to root_url, :notice => "Login failed. Try again."
    end
  end

  def destroy
    cookies.delete(:auth_token)
    redirect_to root_url, :notice => "Logged out!"
  end
  
  private
  
  def session_params
    params.permit(:email, :password)
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # before_action :set_song, only: [:show, :edit, :update, :destroy]
  # before_action :fav_song, only: [:add_favorite, :remove_favorite]

  def create
    if current_user
      if params["playlist_id"] == ""
        @playlist = current_user.playlists.find_by_name("All")
      else
        @playlist = Playlist.find(params["playlist_id"])
      end
        if Song.where(url: params["song_url"], user_id: current_user.id) != []
          @song = Song.where(url: params["song_url"], user_id: current_user.id).first
          @playlist.songs << @song
        elsif Song.where(url: params["song_url"]) != []
          @x = Song.where(url: params["song_url"]).first
          @song = current_user.songs.create(url: @x.url, title: @x.title, album: @x.album, artist: @x.artist, duration: @x.duration, stream_id: @x.stream_id, genre: @x.genre, source_creator_id: @x.source_creator_id, source_creator_username: @x.source_creator_username, source_artwork: @x.source_artwork, source_play_count: @x.source_play_count, source_download_count: @x.source_download_count, source_favorites_count: @x.source_favorites_count, source_upload_date: @x.source_upload_date, source_genre: @x.source_genre, source_title: @x.source_title)
          @playlist.songs << @song
        else
          client = SoundCloud.new(:client_id => ENV['SOUNDCLOUD_CLIENT_ID'])
          track = client.get('/resolve', :url => params["song_url"])
          @song = current_user.songs.create(url: params["song_url"], title: params["song_title"], album: params["song_album"], artist: params["song_artist"], duration: track["duration"], stream_id: track["id"], genre: params["song_genre"], source_creator_id: track["user_id"], source_creator_username: track["user"]["username"], source_artwork: track["artwork_url"], source_play_count: track["playback_count"], source_download_count: track["download_count"], source_favorites_count: track["favoritings_count"], source_upload_date: track["created_at"], source_genre: track["genre"], source_title: track["title"])
          @playlist.songs << @song
        end
    end
    respond_to do |format|
        format.js
    end
  end

  def remove
    @order_id = params["order_id"]
    PlaylistOrder.find(@order_id).destroy
    respond_to do |format|
      format.js
    end
  end

  def favorite
    @song_id = PlaylistOrder.find(params["order_id"]).song_id
    Favorite.create(user_id: current_user.id, song_id: @song_id)
    redirect_to root_url
  end

  def unfavorite
    @song_id = PlaylistOrder.find(params["order_id"]).song_id
    Favorite.where(user_id: current_user.id, song_id: @song_id).first.destroy
    redirect_to root_url
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_song
    #   @song = Song.find(params[:id])
    #   @playlist = Playlist.find(params[:playlist_id])
    # end

    # def fav_song
    #   @song = Song.find(params[:id])
    # end

    # # Never trust parameters from the scary internet, only allow the white list through.
    # def add_song_params
    #   params.require(:song).permit(:url)
    # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		if current_user
			@user_client = SoundCloud.new(:access_token => current_user.sc_access_token)
		end
		respond_to do |format|
	      format.html
	  end
	end

	def auth
		sc_client = SoundCloud.new({
			:client_id     => ENV['SOUNDCLOUD_CLIENT_ID'],
			:client_secret => ENV['SOUNDCLOUD_CLIENT_SECRET'],
			:redirect_uri  => 'http://localhost:3000/auth_user',
		})
		tokens = sc_client.exchange_token(:code => params[:code])
		current_user.update(sc_access_token: tokens["access_token"], sc_expiration: tokens["expires_in"], sc_refresh_token: tokens["refresh_token"])
		redirect_to root_url
	end

	def create
		@user = User.create(email: params["email"], password: params["password"])
		cookies.permanent[:auth_token] = @user.auth_token
		sc_client = SoundCloud.new({
			:client_id     => ENV['SOUNDCLOUD_CLIENT_ID'],
			:client_secret => ENV['SOUNDCLOUD_CLIENT_SECRET'],
			:redirect_uri  => 'http://localhost:3000/auth_user',
		})
		@url = sc_client.authorize_url()
		respond_to do |format|
	     format.js {}
	 	end
	end


	private

  def user_params
  	params.require(:user).permit(:email, :password, :sc_access_token)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApolloApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<script src="http://connect.soundcloud.com/sdk.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>

</body>
</html>

app/views/playlists/create.js.erb
$(document).ready(function(){
  $('#all-playlists').append("<li><%=@playlist.name%></li>");
  $('#new-playlist-name').val('');
});

app/views/playlists/single_fetch.js.erb
$(document).ready(function(){
  $('#main-container').html('');
  var html = "<ul class='playlist-main-view' id='<%= @playlist.id %>'> <% @playlist.songs.each do |song| %><li><%= song.title %>,<%= song.artist %>,<%= song.url %></li><% end %></ul>"
  
  $('#main-container').append(html);
});

app/views/songs/create.js.erb
$(document).ready(function(){
  $('#playlist-main-view').append("<li><%= @song.title %>,<%= @song.artist %>,<%= @song.url %></li>");
});

app/views/songs/remove.js.erb
$(document).ready(function(){
  $('#<%= @order_id %>').remove();
});

app/views/users/create.js.erb
$(function () { 

window.location.href = "<%= @url %>";

});

app/views/users/index.html.erb
<% if current_user %>
	Local Email: <%= current_user.email %>
<br/>

<br/>

Playlists:</br>
<ul id="all-playlists">
<% current_user.playlists.each do |playlist| %>
<li class="single-playlist" id="<%= playlist.id %>"><%= playlist.name %></li>
<% end %></ul>
</br>
<input type="text" id="new-playlist-name" placeholder="Untitled Playlist"></input>
<button id="create-playlist">Create Playlist </button>


<div id="main-container">
</div>

<input type='text' id='new-song-url' placeholder='Please insert a valid URL here'></input>
<input type='text' id='new-song-playlist-id' placeholder='Playlist ID'></input>
<input type='text' id='new-song-title' placeholder='Title'></input>
<input type='text' id='new-song-artist' placeholder='Artist'></input>
<input type='text' id='new-song-album' placeholder='Album'></input>
<input type='text' id='new-song-genre' placeholder='Genre'></input>
<button id='add-song'>Add Song</button>



<div id="favorite-songs-playlist">
  <h3>Favorites Playlist</h3>
  <ul id= '<%= current_user.playlists.find_by_name('Favorites').id %>'>
  <% current_user.playlists.find_by_name('Favorites').playlist_orders.each do |order| %>
  <li id='<%= order.id %>'>
    <button class='play-song' id='<%= Song.find(order.song_id).stream_id %>'>Play</button>
    <%= Song.find(order.song_id).title %>
    <button class='remove-song'>Remove</button>
    <% if Favorite.where(user_id: current_user.id, song_id: Song.find(order.song_id).id) == [] %>
      <button class='favorite-song'>Favorite</button>
    <% else %>
      <button class='unfavorite-song'>Unfavorite</button>
    <% end %>
  </li>
  <% end %>
  </ul>
</div>



<br/>
	<%= link_to 'Logout', destory_session_path %>


<% else %>
<br/>
<h1>Register for Apollo</h1>
<label>Email:</label><input type="text" id="email-register" placeholder="email@example.com"></input><br/>
<label>Password:</label><input type="password" id="password-register" placeholder="password"></input><br/>
<button id="create_user_submit">Register</button>

<h1>Current User Login</h1>
<label>Email:</label><input type="text" id="email-login" placeholder="email@example.com"></input><br/>
<label>Password:</label><input type="password" id="password-login" placeholder="password"></input><br/>
<button id="user_login_submit">Log In</button>
<% end %>

app/views/users/soundcloud_user_api_calls.html.erb
SoundCloud Username: <%= @user_client.get('/me').username %><br/>

Followers: <%= @user_client.get('/me').followers_count %><br/>

Following: <%= @user_client.get('/me').following_count %><br/>

Full Name: <%= @user_client.get('/me').full_name %><br/>

City: <%= @user_client.get('/me').city %><br/>

Country: <%= @user_client.get('/me').country %><br/>

Public Favorite Counts: <%= @user_client.get('/me').public_favorites_count %><br/>

Currently Online? <%= @user_client.get('/me').online %><br/>

Track Count: <%= @user_client.get('/me').track_count %><br/>

Playlist Count: <%= @user_client.get('/me').playlist_count %><br/>

Website: <%= @user_client.get('/me').website %><br/>

Description: <%= @user_client.get('/me').description %><br/>

API URI: <%= @user_client.get('/me').uri %><br/>

<img src="<%= @user_client.get('/me').avatar_url %>"/>
<br/>